### ISSUE TITLE
Can't use this gmeet bot

### ISSUE THREAD

**Issue by PierreRtec** [gladiaio/gladia-samples#35]
I was trying to use but it's not up to date. Can you fix it please or tell me how to ?

**Comment by jqueguiner** [comment]
Can you describe in detail the problem you are facing, any log ? Any way to reproduce your problem ?

**Comment by PierreRtec** [comment]
Hello, there is the process to reproduce my issue :

1. I clone gmeet-bot gladia sample
2. I edit the DOckerfile to enter my crendentials
3. start this cmd in the terminal : `docker build -t gmeet -f Dockerfile .`
4. then i run it with credentials too ```
docker run -it \
    -e GMEET_LINK=https://meet.google.com/my-gmeet-id \
    -e GMAIL_USER_EMAIL=myuser1234@gmail.com \
    -e GMAIL_USER_PASSWORD=my_gmail_password \
    -e DURATION_IN_MINUTES=1 \ #duration of the meeting to record
    -e GLADIA_API_KEY=YOUR_GLADIA_API_KEY \
    -e GLADIA_DIARIZATION=true \
    -e MAX_WAIT_TIME_IN_MINUTES=2 \ #max wait time in the lobby
    -v $PWD/recordings:/app/recordings \ # local storage for the recording
    -v $PWD/screenshots:/app/screenshots \ # local storage for intermediate bot screenshots
    gmeet
    
    And here is the log of the container : 
    
    `2024-06-02 12:45:11 running: /app/entrypoint.sh
2024-06-02 12:45:11 running keepUpScreen()
2024-06-02 12:45:11 starting google meet recorder...
2024-06-02 12:45:12 start recorder for https://meet.google.com/theId..
2024-06-02 12:45:12 Cleaning screenshots
2024-06-02 12:45:12 starting virtual audio drivers
2024-06-02 12:45:48 Google Sign in
2024-06-02 12:45:48 screenshot
2024-06-02 12:45:48 Done save initial
2024-06-02 12:45:48 No popup
2024-06-02 12:45:48 Disable microphone
2024-06-02 12:45:48 Try to dismiss missing mic
2024-06-02 12:45:48 Allow Microphone
2024-06-02 12:45:48 No Allow Microphone popup
2024-06-02 12:45:48 Try to disable microphone
2024-06-02 12:45:48 No microphone to disable
2024-06-02 12:45:48 Done save microphone
2024-06-02 12:45:48 Disable camera
2024-06-02 12:45:48 assuming missing mic = missing camera
2024-06-02 12:45:48 Done save camera
2024-06-02 12:45:48 authentification already done
2024-06-02 12:45:48 Meet - dau-pztc-yad
2024-06-02 12:45:48 Traceback (most recent call last):
2024-06-02 12:45:48   File "/app/gmeet.py", line 238, in join_meet
2024-06-02 12:45:48     driver.find_element(
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
2024-06-02 12:45:48     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2024-06-02 12:45:48            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
2024-06-02 12:45:48     self.error_handler.check_response(response)
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
2024-06-02 12:45:48     raise exception_class(message, screen, stacktrace)
2024-06-02 12:45:48 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="yDmH0d"]/c-wiz/div/div/div[14]/div[3]/div/div[2]/div[4]/div/div/div[2]/div[1]/div[1]/div[3]/label/input"}
2024-06-02 12:45:48   (Session info: chrome=108.0.5359.124)
2024-06-02 12:45:48 Stacktrace:
2024-06-02 12:45:48 #0 0x55fbf78e32a3 <unknown>
2024-06-02 12:45:48 #1 0x55fbf76a1f77 <unknown>
2024-06-02 12:45:48 #2 0x55fbf76de80c <unknown>
2024-06-02 12:45:48 #3 0x55fbf76dea71 <unknown>
2024-06-02 12:45:48 #4 0x55fbf7718734 <unknown>
2024-06-02 12:45:48 #5 0x55fbf76feb5d <unknown>
2024-06-02 12:45:48 #6 0x55fbf771647c <unknown>
2024-06-02 12:45:48 #7 0x55fbf76fe903 <unknown>
2024-06-02 12:45:48 #8 0x55fbf76d1ece <unknown>
2024-06-02 12:45:48 #9 0x55fbf76d2fde <unknown>
2024-06-02 12:45:48 #10 0x55fbf793363e <unknown>
2024-06-02 12:45:48 #11 0x55fbf7936b79 <unknown>
2024-06-02 12:45:48 #12 0x55fbf791989e <unknown>
2024-06-02 12:45:48 #13 0x55fbf7937a83 <unknown>
2024-06-02 12:45:48 #14 0x55fbf790c505 <unknown>
2024-06-02 12:45:48 #15 0x55fbf7958ca8 <unknown>
2024-06-02 12:45:48 #16 0x55fbf7958e36 <unknown>
2024-06-02 12:45:48 #17 0x55fbf7974333 <unknown>
2024-06-02 12:45:48 #18 0x7fd6ae82bea7 start_thread
2024-06-02 12:45:48 
2024-06-02 12:45:48 
2024-06-02 12:45:48 During handling of the above exception, another exception occurred:
2024-06-02 12:45:48 
2024-06-02 12:45:48 Traceback (most recent call last):
2024-06-02 12:45:48   File "/app/gmeet.py", line 434, in <module>
2024-06-02 12:45:48     asyncio.run(join_meet())
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2024-06-02 12:45:48     return runner.run(main)
2024-06-02 12:45:48            ^^^^^^^^^^^^^^^^
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-06-02 12:45:48     return self._loop.run_until_complete(task)
2024-06-02 12:45:48            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
2024-06-02 12:45:48     return future.result()
2024-06-02 12:45:48            ^^^^^^^^^^^^^^^
2024-06-02 12:45:48   File "/app/gmeet.py", line 265, in join_meet
2024-06-02 12:45:48     driver.find_element(
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
2024-06-02 12:45:48     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2024-06-02 12:45:48            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
2024-06-02 12:45:48     self.error_handler.check_response(response)
2024-06-02 12:45:48   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
2024-06-02 12:45:48     raise exception_class(message, screen, stacktrace)
2024-06-02 12:45:48 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="yDmH0d"]/c-wiz/div/div/div[14]/div[3]/div/div[2]/div[4]/div/div/div[2]/div[1]/div[2]/div[1]/div[1]/button"}
2024-06-02 12:45:48   (Session info: chrome=108.0.5359.124)
2024-06-02 12:45:48 Stacktrace:
2024-06-02 12:45:48 #0 0x55fbf78e32a3 <unknown>
2024-06-02 12:45:48 #1 0x55fbf76a1f77 <unknown>
2024-06-02 12:45:48 #2 0x55fbf76de80c <unknown>
2024-06-02 12:45:48 #3 0x55fbf76dea71 <unknown>
2024-06-02 12:45:48 #4 0x55fbf7718734 <unknown>
2024-06-02 12:45:48 #5 0x55fbf76feb5d <unknown>
2024-06-02 12:45:48 #6 0x55fbf771647c <unknown>
2024-06-02 12:45:48 #7 0x55fbf76fe903 <unknown>
2024-06-02 12:45:48 #8 0x55fbf76d1ece <unknown>
2024-06-02 12:45:48 #9 0x55fbf76d2fde <unknown>
2024-06-02 12:45:48 #10 0x55fbf793363e <unknown>
2024-06-02 12:45:48 #11 0x55fbf7936b79 <unknown>
2024-06-02 12:45:48 #12 0x55fbf791989e <unknown>
2024-06-02 12:45:48 #13 0x55fbf7937a83 <unknown>
2024-06-02 12:45:48 #14 0x55fbf790c505 <unknown>
2024-06-02 12:45:48 #15 0x55fbf7958ca8 <unknown>
2024-06-02 12:45:48 #16 0x55fbf7958e36 <unknown>
2024-06-02 12:45:48 #17 0x55fbf7974333 <unknown>
2024-06-02 12:45:48 #18 0x7fd6ae82bea7 start_thread
2024-06-02 12:45:48 
`
    
```

**Comment by jqueguiner** [comment]
Thanks it looks like Google changed their css and the script is not able to find the xpath of the button anymore
I’ll look into this soon

**Comment by PierreRtec** [comment]
Yes i was thinking about something like that, in the html or css. Maybe you have a function thats captures the subtitles ?
Thanks Jean-Louis for the help !

**Comment by PierreRtec** [comment]
> Thanks it looks like Google changed their css and the script is not able to find the xpath of the button anymore
> I’ll look into this soon 

Hey, What's up over here ? :)

**Comment by tamagoeggo** [comment]
@PierreRtec If you didn’t want to deal with the complexities of implementing this yourself, an alternative is to use the [Recall.ai API](https://www.recall.ai/?utm_source=github&utm_medium=forum_answer&utm_campaign=cant_use_gmeet_bot&utm_content=Recall.ai_API) for your meeting bots instead. It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video from meetings without you needing to spend months to build, scale and maintain these bots.

Disclaimer: I’m one of the founders.

**Comment by PierreRtec** [comment]
> @PierreRtec If you didn’t want to deal with the complexities of implementing this yourself, an alternative is to use the [Recall.ai API](https://www.recall.ai/?utm_source=github&utm_medium=forum_answer&utm_campaign=cant_use_gmeet_bot&utm_content=Recall.ai_API) for your meeting bots instead. It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video from meetings without you needing to spend months to build, scale and maintain these bots.
> 
> Disclaimer: I’m one of the founders.

Thanks, I'll test that and give you fb

**Comment by PierreRtec** [comment]
> Thanks it looks like Google changed their css and the script is not able to find the xpath of the button anymore I’ll look into this soon

Hi Jean-Louis, did you have any updates of the issue ? :) Please let me know, Pierre.

**Comment by IlyaShkurenko** [comment]
also interested in google meet bot. Is it supports live transcribe?

**Comment by lucazin** [comment]
Hello Foks! anyone here got tested  this repo with recording and sound  ?  i can enter on meet record the screen but my big problem i can't do the sound recording..

**Comment by leoeol30** [comment]
Hey @PierreRtec @IlyaShkurenko, check out this code I created based on this issue. I'll submit a pull request later: [GitHub Repo](https://github.com/leoeol30/gmeet-bot).

**Comment by sboudouk** [comment]
The Google Meet Bot needs an update to work with Google's changes. 

You can look up for Recall, it's a service that let you plug a BOT to your meeting and you can choose tu use Gladia underneath :)
